{
  "openapi": "3.0.0",
  "info": {
    "title": "Workout Match",
    "description": "Workout Match is an API for creating and managing customized exercises and workouts. With this API, you can create exercises with sets, reps, and exercise classification (type), as well as group them into workouts that can have a defined difficulty level. Additionally, Workout Match also offers the ability to search for exercises and workouts from other users and copy them to your own account, which is especially useful for those looking for new workout ideas and variations.",
    "contact": {
      "email": "arthurgbsf@gmail.com"
    },
    "version": "1.1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local Database"
    },
    {
      "url": "https://workout-match.onrender.com/api-docs",
      "description": "Production Server"
    }
  ],
  "paths": {
    "/auth/login": {
      "post": {
        "description": "Route for authenticate an user.",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/auth-login"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-login"
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          }
        }
      }
    },
    "/auth/forget_password": {
      "post": {
        "description": "Route to request a temporary password. The password is sent to the user's email, witch is only valid for 15 min.",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/auth-forget-password"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-forget-password"
          },
          "400": {
            "description": "Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error02": {
                    "$ref": "#/components/examples/400error2"
                  },
                  "error04": {
                    "$ref": "#/components/examples/400error4"
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "#/components/responses/404-error0"
          }
        }
      }
    },
    "/auth/change_password": {
      "post": {
        "description": "Route to change password from temporary password.",
        "tags": [
          "Auth"
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/auth-change-password"
        },
        "responses": {
          "200": {
            "$ref": "#/components/responses/200-change-password"
          },
          "400": {
            "description": "Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error02": {
                    "$ref": "#/components/examples/400error2"
                  },
                  "error04": {
                    "$ref": "#/components/examples/400error4"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "$ref": "#/components/responses/404-error0"
          },
          "419": {
            "$ref": "#/components/responses/419-error0"
          }
        }
      }
    },
    "/users": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "user",
            "required": false,
            "schema": {
              "type": "boolean"
            },
            "description": "Optional. Pass 'user = true' to get the logged user information."
          }
        ],
        "description": "Route to get users information.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Users"
                  }
                },
                "examples": {
                  "users": {
                    "value": {
                      "_id": "6447d9c97199225fa3f64dbf",
                      "name": "João da Silva",
                      "email": "joao@example.com"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/404error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/user/{id}": {
      "get": {
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Pass an 'id' to get a thirdparty user information."
          }
        ],
        "description": "Route to get user iformation by 'id'.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                },
                "examples": {
                  "users": {
                    "value": {
                      "_id": "6447d9c97199225fa3f64dbf",
                      "name": "João da Silva",
                      "email": "joao@example.com"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error1"
          },
          "404": {
            "$ref": "#/components/responses/404-error0"
          }
        }
      }
    },
    "/users/user": {
      "post": {
        "description": "Route to create an user.",
        "tags": [
          "User"
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "user": {
                  "value": {
                    "name": "João da Silva",
                    "email": "joao@example.com",
                    "password": "123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User created.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "menssage": {
                    "value": {
                      "menssage": "User created."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "$ref": "#/components/responses/409-error1"
          }
        }
      },
      "put": {
        "description": "Route to update the registered user.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "Update user": {
                  "value": {
                    "name": "João da Silva Barbosa",
                    "email": "joaobarbosa@example.com",
                    "password": "123456"
                  }
                },
                "Update user email": {
                  "value": {
                    "email": "joaobarbosa@example.com"
                  }
                },
                "Update user password": {
                  "value": {
                    "password": "123456"
                  }
                },
                "Update user name": {
                  "value": {
                    "name": "João da Silva Barbosa"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User updated.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Message"
                  }
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "User updated."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error2"
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          },
          "409": {
            "$ref": "#/components/responses/409-error1"
          }       
        }
      },
      "delete": {
        "description": "Route to delete registered user.",
        "tags": [
          "User"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "The user was deleted.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Message"
                  }
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "The user was deleted."
                    }
                  }
                }
              }
            }
          },
          "400": {
           "$ref": "#/components/responses/400-error3"
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
           },
          "404": {
          "$ref": "#/components/responses/404-error2"
          }
        }
      }
    },
    "/exercises": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "user",
            "required": false,
            "schema": {
              "type": "boolean"
            },
            "description": "Optional. Pass 'user = true' to get the logged user exercises."
          }
        ],
        "description": "Route to get all users exercises registered. Exercises copied by an user not appear in this request.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Exercises"
                  }
                },
                "examples": {
                  "exercises": {
                    "value": [
                      {
                        "_id": "644a7d690ff85088d51fcb4c",
                        "exercise": "Push ups",
                        "sets": "5",
                        "reps": "15",
                        "type": "push",
                        "createdBy": "644a7d0d0ff85088d51fcb49",
                        "createdAt": "27/04/2023 às 10:49:29"
                      },
                      {
                        "_id": "644a7db70ff85088d51fcb52",
                        "exercise": "Air Squat",
                        "sets": "3",
                        "reps": "8",
                        "type": "Legs",
                        "createdBy": "644a7d0d0ff85088d51fcb49",
                        "createdAt": "27/04/2023 às 10:50:47"
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/404error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/exercises/exercise/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "schema": {
            "type": "string"
          },
          "required": true,
          "description": "The exercise ID."
        }
      ],
      "get": {
        "description": "Route to get an exercise by id.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Exercise"
                  }
                },
                "examples": {
                  "exercises": {
                    "value": {
                      "_id": "644aac5a0756b40273d69ac0",
                      "exercise": "Australian Pull ups",
                      "sets": "5",
                      "reps": "15",
                      "type": "pull",
                      "createdBy": "644a7d0d0ff85088d51fcb49",
                      "createdAt": "23/04/2023 às 10:23:29",
                      "inWorkouts": []
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error1"
          },
          "404": {
            "$ref": "#/components/responses/404-error0"
          }
        }
      },
      "put": {
        "description": "Route to update an exercise by id.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/exerciseUpdateExamples"
        },
        "responses": {
          "200": {
            "description": "Exercise updated with success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "Exercise updated."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description":"Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/400error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/400error2"
                  }
                }
              }
            }
          },
          "401": {
            "$ref":"#/components/responses/401-error0"
          },
          "404": {
            "description":"Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Route to delete an exercise by id.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Exercise deleted with success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "The exercise was deleted with success."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/400error1"
                  },
                  "error03": {
                    "$ref": "#/components/examples/400error3"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Route to copy an exercise. It can be the user's own or another user's.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Copied with success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "Copied with success."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error1"
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/exercises/exercise": {
      "post": {
        "description": "Route to create an enxercise.",
        "tags": [
          "Exercises"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Exercise"
              },
              "examples": {
                "exercise": {
                  "value": {
                    "exercise": "Pull up",
                    "sets": "5",
                    "reps": "10",
                    "type": "pull"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "The request was successful. The exercise was created.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "Exercise created."
                    }
                  }
                }
              }
            }
          },
          "400":{
            "$ref": "#/components/responses/400-error4"
          },
          "401":{
            "$ref": "#/components/responses/401-error0"
          },
          "404":{
            "$ref": "#/components/responses/404-error2"
          }
        }
      }
    },
    "/workouts": {
      "get": {
        "parameters": [
          {
            "in": "query",
            "name": "user",
            "required": false,
            "schema": {
              "type": "boolean"
            },
            "description": "Optional. Pass 'user = true' to get the logged user workouts."
          }
        ],
        "description": "Route to get all users workouts registered. Workout created by user not appear in this request.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Workouts"
                },
                "examples": {
                  "workouts": {
                    "$ref": "#/components/examples/workouts"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/404error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/workouts/workout": {
      "post": {
        "description": "Route to create an workout.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "workout": {
                  "value": {
                    "workout": "Full Body Basic",
                    "level": "Intermediate",
                    "exercises": [
                      "644a87ae01fbb12d48cdc459",
                      "644a87ae01fbb12d48cdc45b",
                      "644a87ae01fbb12d48cdc45e"
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "The request was successful. The workout was created.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "menssage": {
                    "value": {
                      "menssage": "Workout created."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error4"
          },
          "401": {
            "description": "Unauthorized.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/401error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/401error2"
                  },
                  "error03": {
                    "$ref": "#/components/examples/401error3"
                  }
                }
              }
            }
          },
          "404": {
            "description":"Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/400error2"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/workouts/{id}": {
      "parameters": [
        {
          "in": "path",
          "name": "id",
          "schema": {
            "type": "string"
          },
          "required": true,
          "description": "The workout ID."
        }
      ],
      "get": {
        "description": "Route to get an workout by id.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "items": {
                    "$ref": "#/components/schemas/Workout"
                  }
                },
                "examples": {
                  "workout": {
                    "$ref": "#/components/examples/workout"
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400-error1"
          },
          "404": {
            "$ref": "#/components/responses/404-error0"
          }
        }
      },
      "put": {
        "description": "Route to update an workout by Id. It is possible to add or remove exercises, including the id in the exercises array or removing the id.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/workoutUpdateExamples"
        },
        "responses": {
          "400": {
            "description":"Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/400error1"
                  },
                  "error02": {
                    "$ref": "#/components/examples/400error2"
                  }
                }
              }
            }
          },
          "401": {
            "$ref":"#/components/responses/401-error0"
          },
          "404": {
            "description":"Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Route to delete an workout.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Workout deleted with success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "The workout was deleted with success."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/400error0"
                  },
                  "error01": {
                    "$ref": "#/components/examples/400error1"
                  },
                  "error03": {
                    "$ref": "#/components/examples/400error3"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401-error0"
          },
          "404": {
            "description": "Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "description": "Route to copy an workout. It can be the user's own or another user's.",
        "tags": [
          "Workouts"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Copied with success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "examples": {
                  "message": {
                    "value": {
                      "message": "Copied with success."
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description":"Bad Request.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error01": {
                    "$ref": "#/components/examples/400error1"
                  },
                  "error04": {
                    "$ref": "#/components/examples/400error4"
                  }
                }
              }
            }
          },
          "401": {
            "$ref":"#/components/responses/401-error0"
          },
          "404": {
            "description":"Not Found.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "$ref": "#/components/schemas/Message"
                },
                "examples": {
                  "error0": {
                    "$ref": "#/components/examples/404error0"
                  },
                  "error02": {
                    "$ref": "#/components/examples/404error2"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "temporaryPassword": {
            "type": "string"
          },
          "temporaryPasswordExpiresAt": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "myCreatedWorkouts": {
            "type": "array"
          },
          "myCreatedExercises": {
            "type": "array"
          }
        }
      },
      "Users": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#/components/schemas/User"
        }
      },
      "Message": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string"
          }
        }
      },
      "Exercise": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "exercise": {
            "type": "string"
          },
          "sets": {
            "type": "string"
          },
          "reps": {
            "type": "string"
          },
          "createdBy": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "copiedExerciseId": {
            "type": "string"
          },
          "inWorkouts": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Exercises": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#/components/schemas/Exercise"
        }
      },
      "Workout-exercise-type-array-of-strings": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "workout": {
            "type": "string"
          },
          "level": {
            "type": "string"
          },
          "createdBy": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "copiedWorkoutId": {
            "type": "string"
          },
          "exercises": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Workout": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "workout": {
            "type": "string"
          },
          "level": {
            "type": "string"
          },
          "createdBy": {
            "type": "string"
          },
          "createdAt": {
            "type": "string"
          },
          "updatedAt": {
            "type": "string"
          },
          "copiedWorkoutId": {
            "type": "string"
          },
          "exercises": {
            "type": "array",
            "items": {
              "type": "object",
              "$ref": "#/components/schemas/Exercise"
            }
          }
        }
      },
      "Workouts": {
        "type": "array",
        "items": {
          "type": "object",
          "$ref": "#/components/schemas/Workout"
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "responses": {
      "200-login": {
        "description": "An user's 1 hour authorization token.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "properties": {
                "token": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "response": {
                "$ref": "#/components/examples/token-response"
              }
            }
          }
        }
      },
      "200-forget-password":{
        "description": "A message indicating that the email with the temporary password has been sent.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "response": {
                      "$ref": "#/components/examples/forget-password-response"
                  }
                }
              }
            }
      },
      "200-change-password":{
        "description": "A message indicating the password was successfully changed.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "response": {
                    "$ref": "#/components/examples/change-password-response"
                  }
                }
              }
            }
      },
      "400-error0": {
        "description": "Bad Request.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/400error0"
              }
            }
          }
        }
      },
      "400-error1": {
        "description": "Invalid Id.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/400error1"
              }
            }
          }
        }
      },
      "400-error2": {
        "description": "Not Modified.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/400error2"
              }
            }
          }
        }
      },
      "400-error3": {
        "description": "Not Deleted.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/400error3"
              }
            }
          }
        }
      },
      "400-error4": {
        "description": "Undefined.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/400error4"
              }
            }
          }
        }
      },
      "401-error0": {
        "description": "Unauthorized.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/401error0"
              }
            }
          }
        }
      },
      "401-error1": {
        "description": "To create a workout is required have exercises.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                  "$ref": "#/components/examples/401error1"
              }
            }
          }
        }
      },
      "401-error2": {
        "description": "Is required at least one exercise.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/401error2"
              }
            }
          }
        }
      },
      "401-error3": {
        "description": "There are no copied exercises in your request body.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/401error3"
              }
            }
          }
        }
      },
      "404-error0": {
        "description": "Not Found.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/404error0"
              }
            }
          }
        }
      },
      "404-error1": {
        "description": "No registers.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/404error1"
              }
            }
          }
        }
      },
      "404-error2": {
        "description": "Token not found.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/404error2"
              }
            }
          }
        }
      },
      "409-error0": {
        "description": "Conflict.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/409error0"
              }
            }
          }
        }
      },
      "409-error1": {
        "description": "Email have already registered.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/409error1"
              }
            }
          }
        }
      },
      "419-error0": {
        "description": "Authentication Timeout.",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "$ref": "#/components/schemas/Message"
            },
            "examples": {
              "error": {
                "$ref": "#/components/examples/419error0"
              }
            }
          }
        }
      }
    },
    "requestBodies": {
      "auth-login":{
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/User"
            },
            "examples": {
              "user": {
                "$ref": "#/components/examples/user-login"
              }
            }
          }
        }
      },
      "auth-forget-password":{
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/User"
            },
            "examples": {
              "user": {
                  "$ref": "#/components/examples/user-forget-password"
              }
            }
          }
        }
      },
      "auth-change-password":{
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/User"
            },
            "examples": {
              "user": {
                "$ref": "#/components/examples/user-change-password" 
              }
            }
          }
        }
      },
      "exerciseUpdateExamples": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Exercise"
            },
            "examples": {
              "update": {
                "value": {
                  "exercise": "Deadlift",
                  "sets": "8",
                  "reps": "10",
                  "type": "Fullbody"
                }
              },
              "exercise-update": {
                "value": {
                  "exercise": "Deadlift"
                }
              },
              "sets-update": {
                "value": {
                  "sets": "8"
                }
              },
              "reps-update": {
                "value": {
                  "reps": "10"
                }
              },
              "type-update": {
                "value": {
                  "type": "Fullbody"
                }
              }
            }
          }
        }
      },
      "workoutUpdateExamples": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Workout-exercise-type-array-of-strings"
            },
            "examples": {
              "update": {
                "value": {
                  "workout": "Full Body Basic",
                  "level": "Intermediate",
                  "exercises": [
                    "644a87ae01fbb12d48cdc459",
                    "644a87ae01fbb12d48cdc45b",
                    "644a87ae01fbb12d48cdc45e"
                  ]
                }
              },
              "workout-update": {
                "value": {
                  "workout": "Full Body"
                }
              },
              "level-update": {
                "value": {
                  "level": "Advanced"
                }
              },
              "exercise-update-add": {
                "value": {
                  "exercises": [
                    "644a87ae01fbb12d48cdc459",
                    "644a87ae01fbb12d48cdc45b",
                    "644a87ae01fbb12d48cdc45e",
                    "644a87ae01fbb12d48cdc45b"
                  ]
                }
              },
              "exercise-update-remove": {
                "value": {
                  "exercises": [
                    "644a87ae01fbb12d48cdc459",
                    "644a87ae01fbb12d48cdc45b"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "examples": {
      "400error0": {
        "value": {
          "message": "Bad Request."
        }
      },
      "400error1": {
        "value": {
          "message": "Invalid Id."
        }
      },
      "400error2": {
        "value": {
          "message": "Not Modified."
        }
      },
      "400error3": {
        "value": {
          "message": "Not Deleted."
        }
      },
      "400error4": {
        "value": {
          "message": "Undefined."
        }
      },
      "401error0": {
        "value": {
          "message": "Unauthorized."
        }
      },
      "401error1": {
        "value": {
          "message": "To create a workout is required have exercises."
        }
      },
      "401error2": {
        "value": {
          "message": "Is required at least one exercise."
        }
      },
      "401error3": {
        "value": {
          "message": "There are no copied exercises in your request body."
        }
      },
      "404error0": {
        "value": {
          "message": "Not Found."
        }
      },
      "404error1": {
        "value": {
          "message": "No registers."
        }
      },
      "404error2": {
        "value": {
          "message": "Token not found."
        }
      },
      "409error0": {
        "value": {
          "message": "Conflict."
        }
      },
      "409error1": {
        "value": {
          "message": "Email have already registered."
        }
      },
      "419error0": {
        "value": {
          "message": "Authentication Timeout."
        }
      },
      "token-response": {
        "value": {
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ3ZDljOTcxOTkyMjVmYTNmNjRkYmYiLCJlbWFpbCI6ImpvYW9AZXhhbXBsZS5jb20iLCJpYXQiOjE2ODI0MzExNTMsImV4cCI6MTY4MjQzNDc1M30.rtOo35iXZGI_GjBt589o4dZ6vquDAyF8pmoyKRa-YTY"
        }
      },
      "user-login":{
        "value":{
          "email": "marie-example@example.com",
				  "password":"123"
        }
      },
      "user-forget-password":{
        "value":{
          "email": "marie-example@example.com"
        }
      },
      "forget-password-response":{
        "value":{
          "message": "Email successfully sent."
        }
      },
      "user-change-password":{
        "value":{
          "email": "marie-example@example.com",
          "temporaryPassword": "f84125710306ed2bee0c",
          "password": "abc"
        }
      },
      "change-password-response":{
        "value":{
          "message": "Password successfully changeded."
        }
      },
      "user-john-response":{
        "value":{
          "_id": "645db67a6fa1a3866bfb096d",
          "name": "john Example",
          "email": "john-example@example.com",
          "myCreatedWorkouts": [],
          "myCreatedExercises": []
        }
      },
      "user-peter-response":{
        "value":{
          "_id": "645db67a6fa1a3866bfb096d",
          "name": "john Example",
          "email": "john-example@example.com",
          "myCreatedWorkouts": [],
          "myCreatedExercises": []
        }
      },
      "workouts": {
        "value": [
          {
            "_id": "644a7e1b0ff85088d51fcb5a",
            "workout": " Full Body Basic",
            "level": "beginner",
            "createdBy": "644a7d0d0ff85088d51fcb49",
            "createdAt": "27/04/2023 às 10:52:27",
            "exercises": [
              {
                "_id": "644a7d960ff85088d51fcb4f",
                "exercise": "Australian Pull ups",
                "sets": "3",
                "reps": "8",
                "type": "Pull",
                "createdAt": "27/04/2023 às 10:50:14"
              },
              {
                "_id": "644a7db70ff85088d51fcb52",
                "exercise": "Squats",
                "sets": "3",
                "reps": "8",
                "type": "Legs",
                "createdAt": "27/04/2023 às 10:50:47 "
              },
              {
                "_id": "644a8c03e716fd14d9a552b0",
                "exercise": "Push ups",
                "sets": "3",
                "reps": "8",
                "type": "Push",
                "createdAt": "27/04/2023 às 11:51:47 "
              }
            ],
            "updatedAt": "27/04/2023 às 13:23:17 "
          },
          {
            "_id": "644a7e1b0ff85088d51fcb5b",
            "workout": " Full Body Advanced",
            "level": "Advanced",
            "createdBy": "644a7d0d0ff85088d51fcb48",
            "createdAt": "27/04/2023 às 10:52:27",
            "exercises": [
              {
                "_id": "644a7d960ff85088d51fcb4g",
                "exercise": "Pull ups",
                "sets": "3",
                "reps": "8",
                "type": "Pull",
                "createdAt": "27/04/2023 às 10:50:14"
              },
              {
                "_id": "644a7db70ff85088d51fcb51",
                "exercise": "Air Squats",
                "sets": "3",
                "reps": "8",
                "type": "Legs",
                "createdAt": "27/04/2023 às 10:50:47 "
              },
              {
                "_id": "644a8c03e716fd14d9a552b2",
                "exercise": "Dips",
                "sets": "3",
                "reps": "8",
                "type": "Push",
                "createdAt": "27/04/2023 às 11:51:47 "
              }
            ],
            "updatedAt": "27/04/2023 às 13:23:17 "
          }
        ]
      },
      "exercises-basic": {
        "value": [
          {
            "_id": "644a7d960ff85088d51fcb4f",
            "exercise": "Australian Pull ups",
            "sets": "3",
            "reps": "8",
            "type": "Pull",
            "createdAt": "27/04/2023 às 10:50:14"
          },
          {
            "_id": "644a7db70ff85088d51fcb52",
            "exercise": "Squats",
            "sets": "3",
            "reps": "8",
            "type": "Legs",
            "createdAt": "27/04/2023 às 10:50:47 "
          },
          {
            "_id": "644a8c03e716fd14d9a552b0",
            "exercise": "Push ups",
            "sets": "3",
            "reps": "8",
            "type": "Push",
            "createdAt": "27/04/2023 às 11:51:47 "
          }
        ]
      },
      "exercises-advanced": {
        "value": [
          {
            "_id": "644a7d960ff85088d51fcb4g",
            "exercise": "Pull ups",
            "sets": "3",
            "reps": "8",
            "type": "Pull",
            "createdAt": "27/04/2023 às 10:50:14"
          },
          {
            "_id": "644a7db70ff85088d51fcb51",
            "exercise": "Air Squats",
            "sets": "3",
            "reps": "8",
            "type": "Legs",
            "createdAt": "27/04/2023 às 10:50:47 "
          },
          {
            "_id": "644a8c03e716fd14d9a552b2",
            "exercise": "Dips",
            "sets": "3",
            "reps": "8",
            "type": "Push",
            "createdAt": "27/04/2023 às 11:51:47 "
          }
        ]
      },
      "getUserByIdAndCheck": {
        "value": {
          "message": "User not found."
        }
      },
      "validateExercisesError01": {
        "value": {
          "message": "Exercises not found."
        }
      },
      "validateExercisesError02": {
        "value": {
          "message": "Is required at least one exercise."
        }
      },
      "validateExercisesError03": {
        "value": {
          "message": "You need to copy theses exercises first : '644a7d690ff85088d51fcb4c'"
        }
      },
      "setRefWorkoutInExercise": {
        "value": {
          "message": "Workout not found."
        }
      },
      "workout": {
        "value": {
          "_id": "644a7e1b0ff85088d51fcb5a",
          "workout": " Full Body Basic",
          "level": "beginner",
          "createdBy": "644a7d0d0ff85088d51fcb49",
          "createdAt": "27/04/2023 às 10:52:27",
          "exercises": [
            {
              "_id": "644a7d960ff85088d51fcb4f",
              "exercise": "Australian Pull ups",
              "sets": "3",
              "reps": "8",
              "type": "Pull",
              "createdAt": "27/04/2023 às 10:50:14"
            },
            {
              "_id": "644a7db70ff85088d51fcb52",
              "exercise": "Squats",
              "sets": "3",
              "reps": "8",
              "type": "Legs",
              "createdAt": "27/04/2023 às 10:50:47 "
            },
            {
              "_id": "644a8c03e716fd14d9a552b0",
              "exercise": "Push ups",
              "sets": "3",
              "reps": "8",
              "type": "Push",
              "createdAt": "27/04/2023 às 11:51:47 "
            }
          ],
          "updatedAt": "27/04/2023 às 13:23:17 "
        }
      }
    }
  }
}